GET users endpoint
codelouisvilleproject/javascript-api pull request #25
Opened 2018-02-13 00:03 UTC by mattpeyton

GET method that serves an array of all users.

2018-02-14 21:06 UTC, bschuste commented
Looks good to me

2018-02-14 23:39 UTC, bschuste approved these changes
We get the whole list of users info, might be useful to be able to get the info about one user.

2018-02-15 04:00 UTC, bretwalker requested changes

2018-02-15 04:00 UTC, bretwalker commented on api/swagger/swagger.yaml
> +              $ref: "#/definitions/User"
The objects being returned do not match the schema defined by `#/definitions/User`.

Here's what Swagger UI says the response should look like:
```
[
  {
    "firstName": "string",
    "lastName": "string",
    "birthMonth": 0,
    "birthDay": 0,
    "birthYear": 0,
    "email": "string"
  }
]
```

Here's an actual response:
```
[
  {
    "id": "1",
    "firstName": "Jane",
    "lastName": "Smith",
    "birthDate": "1980-01-27",
    "email": "jane.smith@example.com"
  }
]
```

You'll need to manipulate the object you get back from the database to match the format defined in Swagger.

2018-02-15 04:02 UTC, bretwalker commented
@bschuste Yes, we should add `GET /users/{user id}` to our list of endpoints for sure.

We also need to update our user models and endpoints to support the new fields @cjrobles12 added https://github.com/codelouisvilleproject/database-schema/commit/36663dedc0b890061ae20fc3c45209210abd71a0.

2018-02-15 04:09 UTC, bretwalker commented on api/swagger/swagger.yaml
> +              $ref: "#/definitions/User"
You can use compisition to inherit from the `User` definition. You'll want to have all of its fields in your objects, and you'll want to add an the ID. You could call your definition `UserWithId`.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#models-with-composition

2018-02-16 03:19 UTC, mattpeyton commented
Thanks for pointing out the discrepancy, Bret.  I updated the swagger.yaml and the controller to match each other and made sure that the response matched the story that I'm working from.  Any future changes we would like to make to the response array (adding or removing attributes) should be pretty straightforward.

2018-02-16 15:33 UTC, bretwalker commented
I actually think it would be best if the PUT/GET were as similar as possible.
Did you see my note about using composition to inherit from Brigitte's definition? You should be able to inherit from her `User` definition and then you only need to add an ID field, since her definition contains the other fields already.
This way, it reduces code, makes our API more consistent, and lets us make updates in one place.
If you need help with this, just let me know.
Thanks!

2018-02-17 21:45 UTC, mattpeyton commented
Bret. Sure. I've changed the swagger.yaml to inherit Brigitte's definition and add an id. Before I go any further, do I need the result to match the GET/user endpoint story or should we update the story to show a more detailed array (full birthdate + id)?

2018-02-18 22:07 UTC, bretwalker approved these changes
Looks great!

2018-02-19 23:02 UTC, merged